[package]
name = "totally-legit"
version = "0.0.1"
edition = "2024"

[lib]
name = "totally_legit"

[dependencies]
totally-legit-core = { path = "../totally_legit_core" }
totally-legit-util = { path = "../totally_legit_util" }
